-- 0910.

DROP FUNCTION IF EXISTS LEGACY.SPLIT_STR;
CREATE FUNCTION LEGACY.SPLIT_STR(
xx VARCHAR(500),
delim VARCHAR(12),
pos INT
)
RETURNS VARCHAR(500)
RETURN REPLACE(SUBSTRING(SUBSTRING_INDEX(xx, delim, pos),
LENGTH(SUBSTRING_INDEX(xx, delim, pos -1)) + 1),
delim, '')
;
