INSERT INTO M_B2C_ADDON(MAP_RULE_ID,
                        MAP_TYPE,
                        TGT_OFFER_TYPE,
                        SRC_COMBO_LIST,
                        TGT_OFFER_CD,
                        TGT_OFFER_NAME,
                        TGT_OFFER_SHORT_DESC,
                        TGT_OFFER_CUST_DESC,
                        TGT_OFFER_INT_DESC,
                        P_ADDON_TYPE,
                        P_PRODUCT_PYPE,
                        P_SUBSCRIBER_TYPE,
                        P_SEGMENT_ELIGIBILITY,
                        P_1ST_LEVEL_HIER,
                        P_2ND_LLEVEL_HIER,
                        P_3RD_PARTY_SERVICE,
                        P_3RD_PARTY_SERVICE_VENDOR,
                        P_VOICE_BILLING_INCREMENT)
	SELECT
		CAST(TRIM(MAP_RULE_ID) AS SIGNED INTEGER)	AS MAP_RULE_ID,
		TRIM(MAP_TYPE)                              AS MAP_TYPE,
		TRIM(TGT_OFFER_TYPE)                        AS TGT_OFFER_TYPE,
		TRIM(SRC_COMBO_LIST)                        AS SRC_COMBO_LIST,
		TRIM(TGT_OFFER_CD)                          AS TGT_OFFER_CD,
		TRIM(TGT_OFFER_NAME)                        AS TGT_OFFER_NAME,
		TRIM(TGT_OFFER_SHORT_DESC)                  AS TGT_OFFER_SHORT_DESC,
		TRIM(TGT_OFFER_CUST_DESC)                   AS TGT_OFFER_CUST_DESC,
		TRIM(TGT_OFFER_INT_DESC)                    AS TGT_OFFER_INT_DESC,
		TRIM(P_ADDON_TYPE)                          AS P_ADDON_TYPE,
		TRIM(P_PRODUCT_PYPE)                        AS P_PRODUCT_PYPE,
		TRIM(P_SUBSCRIBER_TYPE)                     AS P_SUBSCRIBER_TYPE,
		TRIM(P_SEGMENT_ELIGIBILITY)                 AS P_SEGMENT_ELIGIBILITY,
		TRIM(P_1ST_LEVEL_HIER)                      AS P_1ST_LEVEL_HIER,
		TRIM(P_2ND_LLEVEL_HIER)                     AS P_2ND_LLEVEL_HIER,
		TRIM(P_3RD_PARTY_SERVICE)                   AS P_3RD_PARTY_SERVICE,
		TRIM(P_3RD_PARTY_SERVICE_VENDOR)            AS P_3RD_PARTY_SERVICE_VENDOR,
		TRIM(P_VOICE_BILLING_INCREMENT)             AS P_VOICE_BILLING_INCREMENT
	  FROM
	    M_B2C_ADDON_LDR;
		
CALL WORK.LOGIT_BO_MAPPINGS('020_LOAD_M_B2C_ADDON.sql', 'LEGACY', 'INSERT', ROW_COUNT());