CREATE TABLE BO_MAPPING_LOG
(
	SEQ_NO		INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	DOMAIN		VARCHAR(10),
	MDM_NAME	VARCHAR(255),
	SCRIPT_NAME	VARCHAR(80),
	SCRIPT_PART	VARCHAR(50),
	ROW_NUM		INTEGER,
	NOTE		VARCHAR(100),
	EVENT_DATE	DATETIME
) CHARACTER SET UTF8
  ENGINE		MYISAM;