CREATE TABLE REJECT_PARAM
(
	REJECT_RULE_ID		VARCHAR(30)	PRIMARY KEY,
	REJECT_CONDITION	VARCHAR(400),
	DESCRIPTION			VARCHAR(100),
	NOTE				VARCHAR(400)
) CHARACTER SET UTF8
  ENGINE		MYISAM;

CALL LOGIT_ACC('INIT', '080_WORK_REJECT_PARAM.sql', 'WORK', 'CREATED', 1);