INSERT INTO RUNTIME_PARAMS(PARAM_NAME, PARAM_VALUE) VALUES('CHECK_NOT_NULL', 'TRUE');
INSERT INTO RUNTIME_PARAMS(PARAM_NAME, PARAM_VALUE) VALUES('CHECK_UNIQENESS', 'TRUE');

CALL LOGIT_ACC('INIT', '130_WORK_RUNTIME_PARAMS_INSERTION.sql', 'WORK', 'INSERT', 2);