-- NAS 10.04 beégetések bõvítése
SET @EFF_DT = CAST(LEGACY.CONFIG('DEF_EFF_DATE',NULL) AS DATETIME);
SET @EXP_DT = CAST(LEGACY.CONFIG('DEF_EXP_DATE',NULL) AS DATETIME);
SET @OFFER_TYPE_MAIN = LEGACY.CONFIG('OFFER_TYPE_MAIN',NULL);
SET @OFFER_TYPE_ADDON = LEGACY.CONFIG('OFFER_TYPE_ADDON',NULL);

insert into MDM.INS_OFFER (
TENANT_ID,
OFFER_INST_ID,
CUST_ID,
CUST_TYPE,
USER_ID,
OFFER_ID,
OFFER_TYPE,
BRAND_ID,
ORDER_NAME,
STATE,
EFFECTIVE_DATE,
EXPIRE_DATE,
SALE_TYPE,
DONE_CODE,
EXPIRE_PROCESS_TYPE,
CHANNEL_TYPE,
OS_STATE)

select 
 distinct
'22',
CONCAT(MAIN_SOC_SEQ_NO,VERIS_OFFER_ID),
CA,
'3',
CONCAT(BAN,'_',BEN,'_',CTN),
VERIS_OFFER_ID,
-- CASE WHEN OFFER_TYPE = 'T' THEN 'OFFER_PLAN_BOSS' ELSE 'OFFER_VAS_CBOSS' END, mgy 2016.06.28
CASE WHEN OFFER_TYPE = 'T' THEN @OFFER_TYPE_MAIN ELSE @OFFER_TYPE_ADDON END,
'0',
OFFER_NAME,
CASE WHEN 
  SOC_EXPIRATION_DATE < SYSDATE() THEN '7' 
     WHEN
  SOC_EFFECTIVE_DATE > SYSDATE() THEN '7' 
  ELSE '1'
END STATE,
CASE WHEN SOC_EFFECTIVE_DATE IS NULL THEN @EFF_DT
   WHEN  SOC_EFFECTIVE_DATE > @EXP_DT THEN @EFF_DT
     ELSE SOC_EFFECTIVE_DATE
     END AS EFFECTIVE_DATE,
CASE WHEN SOC_EXPIRATION_DATE IS NULL THEN @EXP_DT
     WHEN SOC_EXPIRATION_DATE > @EXP_DT THEN @EXP_DT
     ELSE SOC_EXPIRATION_DATE END AS EXPIRE_DATE,
'0',
null,
'0',
'99999',
'0' -- OS_STATE
FROM 
LEGACY.SOC_FEATURE_OFFER_MAPPING
 WHERE 
-- MAIN_FEATURE_FLAG = 'Y' AND
 SOC_CODE = MAIN_SOC_CODE
-- AND CTN IN (SELECT DISTINCT CTN FROM LEGACY.SOC_FEATURE_OFFER_MAPPING WHERE OFFER_TYPE = 'T')
;

-- nk0513: updateljuk azoknak az usereknek a statuszat, es lejarati datumat amelyeknek nem aktiv a main offeruk;
/*    UPDATE MDM.INS_USER A JOIN    
  (SELECT USER_ID, MAX(case EXPIRE_DATE when '2099-12-31 23:59:59' then EFFECTIVE_DATE else EXPIRE_DATE end) EXPIRE_DATE  FROM MDM.INS_OFFER 
   WHERE OFFER_TYPE = 'OFFER_PLAN_BBOSS' -- ABO 07/06
  GROUP BY USER_ID
  HAVING MAX(STATE) = '7' AND MIN(STATE) <> 1) X
    ON A.USER_ID = X.USER_ID
  SET A.STATE = '5', A.PRE_DESTORY_TIME = X.EXPIRE_DATE, A.EXPIRE_DATE = X.EXPIRE_DATE;*/

-- nk0513: updateljuk azoknak az offereknek a statuszat, amelyeknek nem aktiv a main offeruk;

  UPDATE MDM.INS_OFFER A 
  JOIN    
  	( SELECT USER_ID, MAX(case EXPIRE_DATE when @EXP_DT then EFFECTIVE_DATE else EXPIRE_DATE end) EXPIRE_DATE  
  		FROM MDM.INS_OFFER 
         WHERE OFFER_TYPE = @OFFER_TYPE_MAIN -- ABO 07/06
  GROUP BY USER_ID
  HAVING MAX(STATE) = '7' AND MIN(STATE) > 1) X
    ON A.USER_ID = X.USER_ID
  AND A.OFFER_TYPE = @OFFER_TYPE_ADDON
  SET A.STATE = '7', A.EXPIRE_DATE = X.EXPIRE_DATE;
