-- 9400.
USE LEGACY;

UPDATE MDM.ADMIN_BOARD SET READY=1 WHERE DOMAIN='BO_B2B_OFFER_'AND TABLE_NAME='INS_OFFER';

UPDATE MDM.ADMIN_BOARD SET READY=1 WHERE DOMAIN='BO_B2B_OFFER_'AND TABLE_NAME='INS_OFF_INS_USER';

